# Generated by Django 5.2.5 on 2025-09-09 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=20)),
                ('battery_health', models.IntegerField(default=100)),
                ('issues', models.JSONField(default=list)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health_data', models.JSONField(default=dict)),
                ('improvement_tips', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='myapp_valua_user_id_19844e_idx'), models.Index(fields=['created_at'], name='myapp_valua_created_e034fa_idx')],
            },
        ),
    ]
